### ISSUE TITLE
Multiple Elixir failing tests intermittently

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1735]
After applying the fix for #1730, two Elixir tests are still failing in Windows.

## Expected Behavior
`make elixir` should pass

## Current Behavior
First failing test:

```
SecurityValidationTest
  * test Non-admin user cannot save a ddoc (140.0ms)
  * test Jerry can save a document normally (234.0ms)
  * test Force basic login (31.0ms)
  * test _session API (0.00ms)
  * test Ddoc writes with admin and replication contexts (235.0ms)
  * test Saving document using the wrong credentials (0.00ms)
  * test Author presence and user security (219.0ms)

  1) test Author presence and user security (SecurityValidationTest)
     test/security_validation_test.exs:136
     Assertion with == failed
     code:  assert resp.status_code() == 403
     left:  201
     right: 403
     stacktrace:
       test/security_validation_test.exs:147: (test)
```

Second failing test:
```
RevisionTest
  * test multiple updates with same _rev raise conflict errors (140.0ms)

  2) test multiple updates with same _rev raise conflict errors (RevisionTest)
     test/conflicts_test.exs:20
     Assertion with == failed
     code:  assert resp.status_code() == 409
     left:  202
     right: 409
     stacktrace:
       test/conflicts_test.exs:91: RevisionTest.assert_conflict/1
       test/conflicts_test.exs:25: (test)
```

Oddly, the test mentioned in https://github.com/apache/couchdb/pull/1726#issuecomment-437644518 isn't failing on Windows.

## Steps to Reproduce (for bugs)
`make elixir` on a Windows box.

## Context
Trying to get the test suite in shape for a 2.3.0 release.

/cc @jaydoane

**Comment by wohali** [comment]
On a subsequent run, a different test fails:

```
BulkDocsTest
  * test bulk docs supplies `id` if not provided in doc (125.0ms)
  * test bulk docs can create, update, & delete many docs per request (296.0ms)
  * test bulk docs raises error for invlaid `new_edits` parameter (141.0ms)
  * test bulk docs raises error for invlaid `docs` parameter (235.0ms)
  * test bulk docs raises error for missing `docs` parameter (140.0ms)
  * test bulk docs raises error for `all_or_nothing` option (266.0ms)
  * test bulk docs can detect conflicts (235.0ms)

  1) test bulk docs can detect conflicts (BulkDocsTest)
     test/bulk_docs_test.exs:45
     Expected 201 and the same number of response rows as in request, but got
     %HTTPotion.Response{
       body: [
         %{
           "accepted" => true,
           "id" => "1",
           "ok" => true,
           "rev" => "2-59422af42db146a6a87b76e5edbeeb44"
         },
         %{
           "id" => "2",
           "ok" => true,
           "rev" => "2-0450643c5eb507fee080a4298e102c9a"
         },
         %{
           "id" => "3",
           "ok" => true,
           "rev" => "2-7c9bd31172bbb3d4097fa45e3a6e2c85"
         },
         %{
           "id" => "4",
           "ok" => true,
           "rev" => "2-2fd866cc031a23ac8ccccb49952a2666"
         },
         %{
           "id" => "5",
           "ok" => true,
           "rev" => "2-3af34b0749ed8322340556d497581836"
         }
       ],
       headers: %HTTPotion.Headers{
         hdrs: %{
           "cache-control" => "must-revalidate",
           "content-length" => "338",
           "content-type" => "application/json",
           "date" => "Tue, 13 Nov 2018 17:49:03 GMT",
           "server" => "CouchDB/2.2.0-878866c1e (Erlang OTP/19)",
           "x-couch-request-id" => "b0a6f69516",
           "x-couchdb-body-time" => "0"
         }
       },
       status_code: 202
     }

     code: resp = bulk_post(docs, db)
     stacktrace:
       test/bulk_docs_test.exs:134: BulkDocsTest.bulk_post/2
       test/bulk_docs_test.exs:57: (test)
```

**Comment by wohali** [comment]
One more:

```
  * test multiple updates with same _rev raise conflict errors (187.0ms)

  1) test multiple updates with same _rev raise conflict errors (RevisionTest)
     test/conflicts_test.exs:20
     Assertion with == failed
     code:  assert resp.status_code() == 409
     left:  202
     right: 409
     stacktrace:
       test/conflicts_test.exs:91: RevisionTest.assert_conflict/1
       test/conflicts_test.exs:25: (test)
```

**Comment by wohali** [comment]
Starting to feel like the tests have some race conditions.

**Comment by jaydoane** [comment]
Unfortunately, I've also noticed numerous elixir tests failing intermittently on macos and linux as well. I think that in general, directly porting JS tests can expose or exacerbate latent races. One way I've been dealing with them is to wrap the success condition in the `retry_until` function.

**Comment by wohali** [comment]
From #1894:

>Unfortunately we've got a lot of failures in Jenkins.
>
>Ignoring the eunit failures, we have 2 types of Elixir failures:
>
>One type is on the partition tests:
>
>    https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fix/1/pipeline/45#step-125-log-2576
>    https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fix/1/pipeline/46#step-123-log-2600
>
>The other is the general test suite:
>
>    https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fix/1/pipeline/48#step-129-log-2659

@garrensmith I'm moving this issue over here off of the PR because I'm going to merge the PR. Thanks for your help when you have time.

**Comment by garrensmith** [comment]
Great. I’ll dive into it next week.


________________________________

**Comment by wohali** [comment]
More failures:

https://travis-ci.org/apache/couchdb/jobs/487532123

```
PartitionDDocTest
  * test PUT /dbname/_design/foo to update (113.0ms)
  * test DELETE /dbname/_design/foo (128.7ms)
  * test GET /dbname/_design_docs (71.8ms)
  1) test GET /dbname/_design_docs (PartitionDDocTest)
     test/partition_ddoc_test.exs:159
     Assertion with == failed
     code:  assert length(body["rows"]) == 1
     left:  0
     right: 1
     stacktrace:
       test/partition_ddoc_test.exs:168: (test)
```

https://travis-ci.org/apache/couchdb/jobs/487532122

```
DelayedCommitsTest
  * test delayed commit (15193.5ms)
  1) test delayed commit (DelayedCommitsTest)
     test/delayed_commits_test.exs:16
     Assertion with == failed
     code:  assert resp.status_code() == 200
     left:  500
     right: 200
     stacktrace:
       (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:737: Enum.each/2
       (ex_unit) lib/ex_unit/on_exit_handler.ex:140: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:126: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

https://travis-ci.org/apache/couchdb/jobs/487532121
```
BulkDocsTest
  * test bulk docs supplies `id` if not provided in doc (497.0ms)
  * test bulk docs raises error for invlaid `new_edits` parameter (334.6ms)
  * test bulk docs raises error for invlaid `docs` parameter (238.1ms)
  * test bulk docs can create, update, & delete many docs per request (396.6ms)
  * test bulk docs emits conflict error for duplicate doc `_id`s (384.0ms)
  * test bulk docs raises conflict error for combined update & delete (471.8ms)
  * test bulk docs can detect conflicts (515.8ms)
  1) test bulk docs can detect conflicts (BulkDocsTest)
     test/bulk_docs_test.exs:47
     Expected 201 and the same number of response rows as in request, but got
     %HTTPotion.Response{
       body: [
         %{
           "accepted" => true,
           "id" => "1",
           "ok" => true,
           "rev" => "2-59422af42db146a6a87b76e5edbeeb44"
         },
         %{
           "id" => "2",
           "ok" => true,
           "rev" => "2-0450643c5eb507fee080a4298e102c9a"
         },
         %{
           "id" => "3",
           "ok" => true,
           "rev" => "2-7c9bd31172bbb3d4097fa45e3a6e2c85"
         },
         %{
           "id" => "4",
           "ok" => true,
           "rev" => "2-2fd866cc031a23ac8ccccb49952a2666"
         },
         %{
           "id" => "5",
           "ok" => true,
           "rev" => "2-3af34b0749ed8322340556d497581836"
         }
       ],
       headers: %HTTPotion.Headers{
         hdrs: %{
           "cache-control" => "must-revalidate",
           "content-length" => "338",
           "content-type" => "application/json",
           "date" => "Fri, 01 Feb 2019 17:40:04 GMT",
           "server" => "CouchDB/2.3.0-0843bd1 (Erlang OTP/21)",
           "x-couch-request-id" => "e75bb02703",
           "x-couchdb-body-time" => "0"
         }
       },
       status_code: 202
     }
     
     code: resp = bulk_post(docs, db)
     stacktrace:
       test/bulk_docs_test.exs:131: BulkDocsTest.bulk_post/2
       test/bulk_docs_test.exs:59: (test)
```

**Comment by janl** [comment]
and one more:

```
* test Simple map functions (348.4ms)

  1) test Simple map functions (BasicsTest)
     test/basics_test.exs:141
     Assertion with == failed
     code:  assert Couch.get("/#{db_name}").body()["doc_count"] == 6
     left:  5
     right: 6
     stacktrace:
       test/basics_test.exs:155: (test)
```

**Comment by wohali** [comment]
Not seeing these now that we moved to `n=1`.
