### ISSUE TITLE
ReshardAllDocsTest errors for Elixir tests in CouchDB test suite

### ISSUE THREAD

**Issue by sarveshtamba** [apache/couchdb#2110]
-CouchDB v2.3(master branch)
-Erlang OTP v21
-Elixir v1.8.2
Following error messages are found intermittently while running CouchDB test suite:-

```
ReshardAllDocsTest
  * test all_docs after splitting all shards on node1 (16905.6ms)

  1) test all_docs after splitting all shards on node1 (ReshardAllDocsTest)
     test/elixir/test/reshard_all_docs_test.exs:21
     ** (RuntimeError) timed out after 10162 ms
     code: wait_job_completed(jobid)
     stacktrace:
       (couchdbtest) test/elixir/lib/couch/db_test.ex:301: Couch.DBTest.retry_until/4
       test/elixir/test/reshard_all_docs_test.exs:32: (test)

  * test all_docs after splitting the same range on all nodes (15679.8ms)

  2) test all_docs after splitting the same range on all nodes (ReshardAllDocsTest)
     test/elixir/test/reshard_all_docs_test.exs:39
     ** (RuntimeError) timed out after 10164 ms
     code: |> Enum.each(fn id -> wait_job_completed(id) end)
     stacktrace:
       (couchdbtest) test/elixir/lib/couch/db_test.ex:301: Couch.DBTest.retry_until/4
       (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:769: Enum.each/2
       test/elixir/test/reshard_all_docs_test.exs:51: (test)


```

**Comment by sarveshtamba** [comment]
Entire test suite for CouchDB v2.3(current master) executes successfully/passes with Erlang v21 and Elixir v1.8 on PowerPC64LE. Closing this issue. Thanks for all your help and support in getting this through.
