### ISSUE TITLE
`make elixir-suite` crashes looking for couch_log

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#3339]
## Description

When I run `make check` the elixir-suite crashes on ~every test with a message of the form

```
AllDocsTest
  * test All Docs tests
02:14:19.931 [error] GenServer #PID<0.684.0> terminating
** (UndefinedFunctionError) function :couch_log.notice/2 is undefined (module :couch_log is not available)
    :couch_log.notice('~s -- (~s) - Connecting...~n', [['2021', 45, '1', 45, '21', 95, '2', 58, '14', 58, '19', 58, '793'], ['127.0.0.1', 58, '15984']])
    (ibrowse 4.0.1) src/ibrowse_http_client.erl:701: :ibrowse_http_client.send_req_1/8
    (stdlib 3.12.1) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.12.1) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.682.0>): {:send_req, {{:url, 'http://127.0.0.1:15984/random-test-db--576460734553537300--576460752303423488', '127.0.0.1', 15984, :undefined, :undefined, '/random-test-db--576460734553537300--576460752303423488', :http, :ipv4_address}, [{'Content-Type', 'application/json'}, {'User-Agent', 'couch-potion'}], :put, "", [basic_auth: {'adm', 'pass'}, inactivity_timeout: 55000], 60000}}
State: {:state, '127.0.0.1', 15984, :undefined, #Reference<0.4227466298.2578448387.155610>, false, :undefined, :undefined, :undefined, :undefined, :undefined, [], false, :undefined, false, [], {[], []}, :undefined, :idle, :undefined, "", 0, 0, [], :undefined, :undefined, :undefined, :undefined, false, :undefined, :undefined, "", :undefined, false, #Reference<0.4227466298.2578579459.155605>, 0, :undefined}
Client #PID<0.682.0> is alive

    (stdlib 3.12.1) gen.erl:167: :gen.do_call/4
    (stdlib 3.12.1) gen_server.erl:219: :gen_server.call/3
    (ibrowse 4.0.1) src/ibrowse.erl:441: :ibrowse.do_send_req/7
    (ibrowse 4.0.1) src/ibrowse.erl:357: :ibrowse.try_routing_request/11
    (couchdbtest 0.1.0) test/elixir/lib/couch.ex:69: Couch.request/3
    (couchdbtest 0.1.0) test/elixir/lib/couch/db_test.ex:169: anonymous fn/2 in Couch.DBTest.create_db/2
    (couchdbtest 0.1.0) test/elixir/lib/couch/db_test.ex:414: Couch.DBTest.retry_until/4
    (couchdbtest 0.1.0) test/elixir/lib/couch/db_test.ex:38: Couch.DBTest.set_db_context/1
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (couchdbtest 0.1.0) test/elixir/test/support/couch_test_case.ex:23: CouchTestCase.__ex_unit_setup_0/1
    (couchdbtest 0.1.0) test/elixir/test/support/couch_test_case.ex:1: CouchTestCase.__ex_unit__/2
    test/elixir/test/all_docs_test.exs:1: AllDocsTest.__ex_unit__/2
    (ex_unit 1.10.4) lib/ex_unit/runner.ex:348: ExUnit.Runner.exec_test_setup/2
    (ex_unit 1.10.4) lib/ex_unit/runner.ex:307: anonymous fn/2 in ExUnit.Runner.spawn_test_monitor/4
    (stdlib 3.12.1) timer.erl:166: :timer.tc/1
    (ex_unit 1.10.4) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
  * test All Docs tests (240.1ms)

  1) test All Docs tests (AllDocsTest)
     test/elixir/test/all_docs_test.exs:16
     ** (KeyError) key :status_code not found in: %HTTPotion.ErrorResponse{message: "{:EXIT, {{:undef, [{:couch_log, :notice, ['~s -- (~s) - Connecting...~n', [['2021', 45, '1', 45, '21', 95, '2', 58, '14', 58, '19', 58, '793'], ['127.0.0.1', 58, '15984']]], []}, {:ibrowse_http_client, :send_req_1, 8, [file: 'src/ibrowse_http_client.erl', line: 701]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, {:gen_server, :call, [#PID<0.684.0>, {:send_req, {{:url, 'http://127.0.0.1:15984/random-test-db--576460734553537300--576460752303423488', '127.0.0.1', 15984, :undefined, :undefined, '/random-test-db--576460734553537300--576460752303423488', :http, :ipv4_address}, [{'Content-Type', 'application/json'}, {'User-Agent', 'couch-potion'}], :put, \"\", [basic_auth: {'adm', 'pass'}, inactivity_timeout: 55000], 60000}}, 60000]}}}"}
     stacktrace:
       (couchdbtest 0.1.0) test/elixir/lib/couch/db_test.ex:170: anonymous fn/2 in Couch.DBTest.create_db/2
       (couchdbtest 0.1.0) test/elixir/lib/couch/db_test.ex:414: Couch.DBTest.retry_until/4
       (couchdbtest 0.1.0) test/elixir/lib/couch/db_test.ex:38: Couch.DBTest.set_db_context/1
       (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (couchdbtest 0.1.0) test/elixir/test/support/couch_test_case.ex:23: CouchTestCase.__ex_unit_setup_0/1
       (couchdbtest 0.1.0) test/elixir/test/support/couch_test_case.ex:1: CouchTestCase.__ex_unit__/2
       test/elixir/test/all_docs_test.exs:1: AllDocsTest.__ex_unit__/2
```

It looks like these errors are occurring on the HTTP client side. I've no idea why ibrowse wants to use couch_log on that side of the setup. I'll admit I don't fully understand the code reuse that might be happening between client and server here.

If I add ERL_LIBS to the environment like so I can run the tests successfully:

```
ERL_LIBS=`pwd`/src make elixir-suite
```

although I'm spammed with messages like

> 02:32:06.360 [error] unknown metric: [:couch_log, :level, :notice]

## Steps to Reproduce

Run `make elixir-suite`

* CouchDB version used: main

**Comment by kocolosk** [comment]
Enh, I can't repro this on a fully clean checkout. Ignore.
