### ISSUE TITLE
Mango test receiving 404/401?

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#935]
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/127/pipeline

```
./test/build/test-run-couch-for-mango.sh \


[ * ] Setup environment ... ok

[ * ] Ensure CouchDB is built ... ok

[ * ] Prepare configuration files ... ok

[ * ] Start node node1 ... ok

[ * ] Check node at http://127.0.0.1:15984/ ... {"couchdb":"Welcome","version":"2.1.1","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

ok

[ * ] Running cluster setup ... ok

[ * ] Developers cluster is set up at http://127.0.0.1:15984.

Admin username: testuser

Password: testpass

Time to hack! ... ESSS................................................................SSSSSSSSSSSSSSSSSSSSSSSSSS...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....................................SS......SSSSSS..........

======================================================================

ERROR: test suite for <class '01-index-crud-test.IndexCrudTests'>

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/nose/suite.py", line 210, in run

    self.setUp()

  File "/usr/lib/python3.4/site-packages/nose/suite.py", line 293, in setUp

    self.setupContext(ancestor)

  File "/usr/lib/python3.4/site-packages/nose/suite.py", line 316, in setupContext

    try_run(context, names)

  File "/usr/lib/python3.4/site-packages/nose/util.py", line 471, in try_run

    return func()

  File "/tmp/tmp.qSlopPxdoL/apache-couchdb-2.1.1-28fae4d/src/mango/test/mango.py", line 248, in setUpClass

    klass.db.create(q=1, n=3)

  File "/tmp/tmp.qSlopPxdoL/apache-couchdb-2.1.1-28fae4d/src/mango/test/mango.py", line 78, in create

    r.raise_for_status()

  File "/usr/lib/python3.4/site-packages/requests/models.py", line 935, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

nose.proxy.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:15984/mango_test_7499828ea3ff4db7a2eb7ea91d4570e3?q=1&n=3

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1

urllib3.connectionpool: DEBUG: http://127.0.0.1:15984 "GET /mango_test_7499828ea3ff4db7a2eb7ea91d4570e3 HTTP/1.1" 404 58

urllib3.connectionpool: DEBUG: http://127.0.0.1:15984 "PUT /mango_test_7499828ea3ff4db7a2eb7ea91d4570e3?q=1&n=3 HTTP/1.1" 401 67

--------------------- >> end captured logging << ---------------------
```

This is especially odd, given Couch was running just fine for a bunch of the tests...then suddenly rejects access.

Is something in the mango test suite changing auth credentials for validation and perhaps not waiting for those changes to take effect?

/cc @nickva @tonysun83

**Comment by willholley** [comment]
Very odd. The Mango tests use the same credentials for all requests (and
the user must be a cluster admin). For CI, this is hard coded to
testuser:testpass.

**Comment by wohali** [comment]
Haven't seen this in months - closing.
